---
- hosts: pgpool
  tasks:
    - name: PGPool check node status
      shell: psql -U hcuser -d hcdb -h localhost -p 9444 -c "show pool_nodes"
      register: result
    - debug:
        var: result.stdout_lines