---
- hosts: pgpool
  tasks:
    - name: replace pgpool.conf file versi terbaru
      copy: 
        src: /data/pgprov/files/pgpool.conf
        dest: /etc/pgpool2/pgpool.conf
        owner: root
        group: root
        mode: 0764         

    - name: Restart service pgpool
      service:
        name: pgpool2
        state: restarted