---
- hosts: pgpool
  become: true
  tasks:
    - name: Menambah User baru untuk akses database
      expect:
        command: pg_md5 --md5auth --username={{ username }} -p
        responses:
          password: "{{ password }}"

    - name: Reload service pgpool
      service:
        name: pgpool2
        state: reloaded
