---
- hosts: pgpool
  tasks:
    - name: copy attach shell
      copy:
        src: ./files/pgpool_attach.sh
        dest: /data/pgpool/pgpool_attach.sh
        owner: root
        group: root
        mode: 0755

    - name: PGPool Attach Node
      shell: /data/pgpool/pgpool_attach.sh

    - name: Restart service pgpool
      service:
        name: pgpool2
        state: restarted